# Generated by Django 4.1.3 on 2022-11-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
